spring:
  application.name: alm-system
  datasource:
    url: jdbc:oracle:thin:@0.0.0.0:1521:free
    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  jackson:
    default-property-inclusion: non_null
server:
  error.include-message: always
  servlet.context-path: /alm
