spring:
  datasource:
    url: jdbc:oracle:thin:@0.0.0.0:1521:free
    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: always
      schema-locations: classpath:demo-schema.sql
      data-locations: classpath:demo-data.sql
